[package]
name = "cargo-borderless"
version = "0.1.0"
edition = "2021"
authors = ["Borderless Technologies GmbH <hello@borderless-technologies.com>"]
keywords = ["cargo", "subcommand", "borderless"]
categories = ["command-line-utilities", "development-tools::cargo-plugins"]

[[bin]]
name = "cargo-borderless"
path = "src/main.rs"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"
anyhow = "1.0"
cliclack = "0.3"
typed-builder = "0.21"
cargo-toml-builder = "0.3"
regex = "1.11"
ed25519-dalek = "2.1"
pem = "3.0"
hex = "0.4"
base64 = "0.22"

[dependencies.borderless-format]
git = "ssh://git@git.borderless-technologies.com:2222/Borderless/borderless.git"
branch = "feature/contract-format"

[dependencies.borderless-hash]
git = "ssh://git@git.borderless-technologies.com:2222/Borderless/borderless.git"
branch = "feature/contract-format"
