# --- The general section defines the package type and the name.
#
# App-Name and App-Module fields can be used to create a "group" out of multiple packages.
# They are simply for organisational purposes, if your application consists of multiple contracts and/or agents.
[Agent]
name = __NAME__
#app_name   = ""
#app_module = ""

# --- The Capabilities section specifies what the agent can or cannot do.
#
# Please don't forget to set the URL whitelist, if you also want to make network calls.
# You can add "*" to the whitelist, to allow connections to everywhere.
[Capabilities]
network = true
websocket = true
url_whitelist = []

# --- The Meta section adds additional information to the package
#
# All fields of this section are optional.
[Meta]
authors = __AUTHORS__
#description = "a short description of your agent"
#documentation = "url to the package's documentation"
#license = "SPDX 2.3 license expression"
#repository = "url to the package's repository"
