---
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v23
        with:
          nix_path: nixpkgs=channel:nixos-stable

      - name: Setup Cachix
        uses: cachix/cachix-action@v12
        with:
          name: nix-community

      - name: Check if shell.nix or flake.nix exists
        id: nix-files
        run: |
          if [ -f flake.nix ]; then
            echo "type=flake" >> $GITHUB_OUTPUT
          elif [ -f shell.nix ]; then
            echo "type=shell" >> $GITHUB_OUTPUT
          elif [ -f default.nix ]; then
            echo "type=default" >> $GITHUB_OUTPUT
          else
            echo "type=none" >> $GITHUB_OUTPUT
          fi

      - name: Build and test
        if: steps.nix-files.outputs.type == 'flake'
        run: |
          nix develop --no-update-lock-file --command cargo fmt --all -- --check
          nix develop --no-update-lock-file --command cargo clippy --all-targets --all-features
          nix develop --no-update-lock-file --command cargo test --verbose
          nix develop --no-update-lock-file --command cargo build --verbose --release

  nix_build:
    name: Nix Build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v23
        with:
          nix_path: nixpkgs=channel:nixos-stable

      - name: Setup Cachix
        uses: cachix/cachix-action@v12
        with:
          name: nix-community

      - name: Build with Nix (Flake)
        if: hashFiles('flake.nix') != ''
        run: |
          nix build --no-update-lock-file .#borderless-cli
