---
name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v23
        with:
          nix_path: nixpkgs=channel:nixos-stable

      - name: Setup Cachix
        uses: cachix/cachix-action@v12
        with:
          name: nix-community

      - name: Check if shell.nix or flake.nix exists
        id: nix-files
        run: |
          if [ -f flake.nix ]; then
            echo "type=flake" >> $GITHUB_OUTPUT
          elif [ -f shell.nix ]; then
            echo "type=shell" >> $GITHUB_OUTPUT
          elif [ -f default.nix ]; then
            echo "type=default" >> $GITHUB_OUTPUT
          else
            echo "type=none" >> $GITHUB_OUTPUT
          fi

      - name: Build and test
        if: steps.nix-files.outputs.type == 'flake'
        run: |
          nix-shell --run "cargo fmt --all -- --check"
          nix-shell --run "cargo clippy --all-targets --all-features -- -D warnings"
          nix-shell --run "cargo check --verbose"
          nix-shell --run "cargo test --verbose"
